Daskom-Lab/2024-Academy

README.md

Added a new role as an academician along with my name, code, and github profile link.

chore: add Farrel Ardya as 2024 academician

---

README.md

Pada commit sebelumnya, saya telah menambahkan informasi pribadi saya ke dalam file README.md. Langkah ini merupakan bagian dari tugas pertemuan minggu lalu untuk memahami alur kerja kolaboratif menggunakan Git dan GitHub, khususnya mengenai pembuatan pull request.
- Menambahkan nama saya beserta tautan ke profil GitHub saya.
- Menambahkan kode asisten untuk identifikasi.
- Menyertakan deskripsi singkat "As an academician" sesuai dengan format yang diberikan.
- Menghapus subheader academician yang sebelumnya ada
Terima kasih atas perhatiannya, dan saya berharap perubahan ini dapat diterima dengan baik!

add {Muhammad Zaenal Abidin Abdurrahman} in README.md

---

README.md

Good evening! My name is Aulia Rahma and I have done my task to open pull request and add my profile as Academician in README.md. Here are the details:
Name: Aulia Rahma
GitHub Link: https://github.com/pieceofaul
Assistant Code: AUL
Thank you so much and have a nice day!

Add Aulia Rahma README.md

---

README.md

Hi to all tentors and mentors, here I would like to do another pull request, but now I'll do both for all of my existing PRs from my friends. Please let me know if there's any I have to change in the upcoming pull requests... Thank you and best regards ✋

EDIT: Update all of existing PRs from my friends (and fixing some typos as well), in one go and in order from the PR timelines.

---

README.md

Hello, mentors, tentors and fellow academicians!
This is my first time diving into the world of GitHub, and I'm excited to submit my very first pull request. In this pull request, I've added my information to the README.md file as a 2024 Academician. Here are the details:
Name: Gibran Reza Al Ghazzali
GitHub Link: https://github.com/bransazza
Assistant Code: GND
Thank you for the opportunity to be part of this amazing academy!

chore: add Gibran Reza Al Ghazzali as 2024 Academician

---

README.md

Hello everyone ! My name is Geraldi and I have done my task to open pull request and add my profile (name, github links profile, and assistant code) as Academician 2024 in README.md. Here are the details:
Name: Geraldi Ridwan Hakim
GitHub Link: https://github.com/geraldirh
Assistant Code: ALD
Thank you so much and have a nice day!

Update add Geraldi Ridwan Hakim README.md

---

README.md

To all the mentors, tentors, and academician. In this pull request, I have made the following changes:
- Added my name (Muhammad Miftah Faqih) to the academician role section included my assistant code (MIT).
- Added my GitHub profile link.
If there is anything that should be changed or added can be communicated further. Thank you.

chore: add Muhammad Miftah Faqih as 2024 Academician

---

README.md

Forked the 2024-Academy repository to my account, named "2024-Academy-SNI".
Created a new branch called "development" in that repository.
Edited the README.md file by adding my name, GitHub link, assistant code, and type "As an academician.", then staged the file with commit message "add Stevannie Pratama in README.md".

chore: add Stevannie Pratama as 2024 Academician.

---

README.md

This pull request updates my profile information within the academician role section by adding my full name, Radif Putra Permana, and assistant code, RAR. Additionally, I’ve included a link to my GitHub profile for reference. Please review the changes and provide any necessary feedback.
[https://github.com/RadifPM/2024-Academy/tree/development](https://github.com/Daskom-Lab/2024-Academy/pull/url)

chore: add {Radif} as 2024 Academician.

---

README.md

Added my name and the link directed to my Github as an Academician.

chore: add Zaidan Abdurrahman Hakim as 2024 Academician.md

---

README.md

Added my name to the list of academicians for the Academy 2024 task.

chore: add {Muhammad Favian Revaldy} as 2024 Academician.

---

Readme.md

I just followed las instruciones [aqui](https://github.com/mhafiz03/2024-Academy/blob/main/resources/git_and_github/010_pull_request.md) (tambahin nama ku di readme dan bikin 1 commit), por favor ayudame en este review. LGTM? (Looks Green To Me)

chore: add Muhammad Hafiz as 2024 Academician

---

Readme.md

I just edit my profile as an academician

chore : add Yattaqi Muazirul Mulki as an academician

---

Readme.md

what I just did in the previous commit is add this thing to README.md to new branch "development", I fork the repo and make new branch there and I added new line that we can see below this paragraph on line 74 and 75
the update:
---
- [Mohammad Fiqri Firmansyah](https://github.com/TakanashaTaryu) [RYU]
> As an Academian

add Mohammad Fiqri Firmansyah in README.md

---

Readme.md

Just adding my name, and github link as an academician in readme.md

 chore: add Rafhan Mazaya Fathurrahman as 2024 Academician

---

Readme.md

Just add my name, and my Github link into Readme.md

chore: add Umar Zaki Gunawan as 2024 Academician

---

Readme.md

Early PR avoid conflict with other academician, but its still using tailwind, next i'll update into pure vanilla css and some styling

Update my website portofolio for assignment task

---

Readme.md

Update Zendin110206 website portfolio for assignment task

---

Readme.md

Adding my personal website link to the Readme.md

Update zaidanah website portfolio for assignment task

---

Readme.md

This Pull Request for adding Radif's Portofolio Website link to the Readme.md (UPDATED)

UPDATE Radif Portofolio Website for academy assignmentDevelopment

---

Readme.md

Adding my portofolio url in readme.md

Update geraldirh Website Portfolio

---

Readme.md

adding Umar Zaki Gunawan portofolio website for an assigment. Pardon for the repeated commit because i found some anomaly

add Umar Zaki Gunawan portofolio website link

---

Readme.md

update adding website link for uki

update adding website link for uki

---

Readme.md

To all Mentors,
I just added my website link to my profile (Muhammad Miftah Faqih).
Thank you.

Update Muhammad Miftah Faqih Website Link in Readme.md

---

Readme.md

This PR adds the url for stevanniep's portfolio website in README.md as assigned

Update Stevannie's website portfolio for assignment task

---

Readme.md

Hi to all tentors and mentors, here I would like to add my brand-new portfolio into the Academy's README.md file. With all the pleasure been given, I'd like to thank for the behalf on the PR here... Thank you once again ☆*: .｡. o(≧▽≦)o .｡.:*☆

feat: Add NUE's portfolio into the README.md.

---

Readme.md

I added a url link for REL's portfolio website as assigned last monday.

Update arelardya website portfolio for assignment task | REL

---

Readme.md

Updating the readme.md file by adding the personal website of academician Muhammad Favian Revaldy [FAV}. Website will be further improved in a later date.

Update lukarukikato portfolio website for assignment task

---

Readme.md

This PR changes the url for RYU's personal website in README.md for assignment 4

Change web url for RYU on Readme.md

---

Readme.md

Hello Mentors,
I just added my website link to my profile (Gibran Reza Al Ghazzali).
Thank you.

Update Gibran Reza Al Ghazzali Website Link in Readme.md

---

Readme.md

Greetings for all of the mentors! My name is Aulia Rahma and I'm one of the academicians in 2024. I do apologize that I accidently close the previous Pull Request and I'm trying to make another one. So, in this PR I want to add my portfolio link, Thank you so much and have a nice day

Update input Aulia Rahma's Portfolio into README

---

Readme.md

This PR changes the url for fai's personal website since the last one is already dead

Change web url for fai

---

assignment/assignment_6.md

**Commit Description:**
- Students will design the backend database schema for their project.
- The assignment includes tasks for creating the database structure and uploading the design to the group repository.
- Submission instructions and timeline are included.
- **Timeline:** September 2, 2024 - September 11, 2024.

Added details for Assignment 6
